// generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{

	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 11: // ['\v','\v']
			return 1
		case r == 12: // ['\f','\f']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 35: // ['#','#']
			return 3
		case r == 38: // ['&','&']
			return 4
		case r == 39: // [''',''']
			return 5
		case r == 40: // ['(','(']
			return 6
		case r == 41: // [')',')']
			return 7
		case r == 42: // ['*','*']
			return 8
		case r == 43: // ['+','+']
			return 9
		case r == 44: // [',',',']
			return 10
		case r == 45: // ['-','-']
			return 11
		case r == 47: // ['/','/']
			return 12
		case 48 <= r && r <= 57: // ['0','9']
			return 13
		case r == 59: // [';',';']
			return 14
		case r == 60: // ['<','<']
			return 15
		case r == 61: // ['=','=']
			return 16
		case r == 62: // ['>','>']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 91: // ['[','[']
			return 19
		case r == 93: // [']',']']
			return 20
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 22
		case 102 <= r && r <= 104: // ['f','h']
			return 18
		case r == 105: // ['i','i']
			return 23
		case 106 <= r && r <= 113: // ['j','q']
			return 18
		case r == 114: // ['r','r']
			return 24
		case r == 115: // ['s','s']
			return 18
		case r == 116: // ['t','t']
			return 25
		case 117 <= r && r <= 118: // ['u','v']
			return 18
		case r == 119: // ['w','w']
			return 26
		case 120 <= r && r <= 122: // ['x','z']
			return 18
		case r == 123: // ['{','{']
			return 27
		case r == 125: // ['}','}']
			return 28

		}
		return NoState
	},

	// S1
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 29

		}
		return NoState
	},

	// S3
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 30

		default:
			return 3
		}

	},

	// S4
	func(r rune) int {
		switch {
		case r == 38: // ['&','&']
			return 31

		}
		return NoState
	},

	// S5
	func(r rune) int {
		switch {
		case 1 <= r && r <= 9: // [\u0001,'\t']
			return 32
		case 11 <= r && r <= 12: // ['\v','\f']
			return 32
		case 14 <= r && r <= 33: // [\u000e,'!']
			return 32
		case r == 34: // ['"','"']
			return 33
		case 35 <= r && r <= 38: // ['#','&']
			return 32
		case 40 <= r && r <= 91: // ['(','[']
			return 32
		case r == 92: // ['\','\']
			return 34
		case 93 <= r && r <= 127: // [']',\u007f]
			return 32

		}
		return NoState
	},

	// S6
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S7
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S8
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S9
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S10
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S11
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S12
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 35
		case r == 47: // ['/','/']
			return 36

		}
		return NoState
	},

	// S13
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 13

		}
		return NoState
	},

	// S14
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S15
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 37

		}
		return NoState
	},

	// S16
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 38

		}
		return NoState
	},

	// S17
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 39

		}
		return NoState
	},

	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},

	// S19
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S20
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S21
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},

	// S22
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 107: // ['a','k']
			return 18
		case r == 108: // ['l','l']
			return 41
		case 109 <= r && r <= 122: // ['m','z']
			return 18

		}
		return NoState
	},

	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 101: // ['a','e']
			return 18
		case r == 102: // ['f','f']
			return 42
		case 103 <= r && r <= 122: // ['g','z']
			return 18

		}
		return NoState
	},

	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 43
		case 102 <= r && r <= 122: // ['f','z']
			return 18

		}
		return NoState
	},

	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 120: // ['a','x']
			return 18
		case r == 121: // ['y','y']
			return 44
		case r == 122: // ['z','z']
			return 18

		}
		return NoState
	},

	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 103: // ['a','g']
			return 18
		case r == 104: // ['h','h']
			return 45
		case 105 <= r && r <= 122: // ['i','z']
			return 18

		}
		return NoState
	},

	// S27
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S28
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S29
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S30
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S31
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S32
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 46

		}
		return NoState
	},

	// S33
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 46

		}
		return NoState
	},

	// S34
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 47

		}
		return NoState
	},

	// S35
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 48

		default:
			return 35
		}

	},

	// S36
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 30

		default:
			return 36
		}

	},

	// S37
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S38
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S39
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},

	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 114: // ['a','r']
			return 18
		case r == 115: // ['s','s']
			return 49
		case 116 <= r && r <= 122: // ['t','z']
			return 18

		}
		return NoState
	},

	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},

	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 115: // ['a','s']
			return 18
		case r == 116: // ['t','t']
			return 50
		case 117 <= r && r <= 122: // ['u','z']
			return 18

		}
		return NoState
	},

	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 111: // ['a','o']
			return 18
		case r == 112: // ['p','p']
			return 51
		case 113 <= r && r <= 122: // ['q','z']
			return 18

		}
		return NoState
	},

	// S45
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 104: // ['a','h']
			return 18
		case r == 105: // ['i','i']
			return 52
		case 106 <= r && r <= 122: // ['j','z']
			return 18

		}
		return NoState
	},

	// S46
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S47
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 46

		}
		return NoState
	},

	// S48
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 48
		case r == 47: // ['/','/']
			return 53

		default:
			return 35
		}

	},

	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 54
		case 102 <= r && r <= 122: // ['f','z']
			return 18

		}
		return NoState
	},

	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 116: // ['a','t']
			return 18
		case r == 117: // ['u','u']
			return 55
		case 118 <= r && r <= 122: // ['v','z']
			return 18

		}
		return NoState
	},

	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 56
		case 102 <= r && r <= 122: // ['f','z']
			return 18

		}
		return NoState
	},

	// S52
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 107: // ['a','k']
			return 18
		case r == 108: // ['l','l']
			return 57
		case 109 <= r && r <= 122: // ['m','z']
			return 18

		}
		return NoState
	},

	// S53
	func(r rune) int {
		switch {

		}
		return NoState
	},

	// S54
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},

	// S55
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 113: // ['a','q']
			return 18
		case r == 114: // ['r','r']
			return 58
		case 115 <= r && r <= 122: // ['s','z']
			return 18

		}
		return NoState
	},

	// S56
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 99: // ['a','c']
			return 18
		case r == 100: // ['d','d']
			return 59
		case 101 <= r && r <= 122: // ['e','z']
			return 18

		}
		return NoState
	},

	// S57
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 60
		case 102 <= r && r <= 122: // ['f','z']
			return 18

		}
		return NoState
	},

	// S58
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 109: // ['a','m']
			return 18
		case r == 110: // ['n','n']
			return 61
		case 111 <= r && r <= 122: // ['o','z']
			return 18

		}
		return NoState
	},

	// S59
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 100: // ['a','d']
			return 18
		case r == 101: // ['e','e']
			return 62
		case 102 <= r && r <= 122: // ['f','z']
			return 18

		}
		return NoState
	},

	// S60
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},

	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},

	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 101: // ['a','e']
			return 18
		case r == 102: // ['f','f']
			return 63
		case 103 <= r && r <= 122: // ['g','z']
			return 18

		}
		return NoState
	},

	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 95: // ['_','_']
			return 21
		case 97 <= r && r <= 122: // ['a','z']
			return 18

		}
		return NoState
	},
}
