// Code generated by "stringer -type BasicKind"; DO NOT EDIT

package types

import "fmt"

const _BasicKind_name = "InvalidCharIntVoid"

var _BasicKind_index = [...]uint8{0, 7, 11, 14, 18}

func (kind BasicKind) String() string {
	if kind < 0 || kind >= BasicKind(len(_BasicKind_index)-1) {
		return fmt.Sprintf("BasicKind(%d)", kind)
	}
	return _BasicKind_name[_BasicKind_index[kind]:_BasicKind_index[kind+1]]
}
